### ISSUE TITLE
온코더 코딩테스트 제안

### ISSUE THREAD

**Issue by jongfeel** [apeach314/study#3]
https://www.oncoder.com/

이번에 2회 코딩 테스트를 진행한다고 합니다.
실제 일부 회사에서 온라인 코딩 테스트 진행하듯이 진행할 수 있고 시간제한도 있기 때문에 긴장감 있게 진행할 수 있습니다.
토요일 오후에 진행하는 거라 특별히 일정이 없으시면 진행해 보시는건 어떨까요?

저는 지난 1회때 테스트 진행했고 두 문제를 맞췄습니다.
그리고 이번 2회 테스트도 진행 예정입니다.

제가 알고리즘  문제 푸는 훈련 관련해서

- Project eular 문제 풀기
- OnCoder 테스트 참여하기

를 진행한지 몇 달 안되는데 알고리즘 관련해서 멘토가 되어 드린게 꽤 다행이라고 생각합니다.

@apeach314 메일로 포워딩

**Comment by apeach314** [comment]
@jongfeel   
내일은 일정도 있고 아직은 단계별 학습이 더 필요할 것 같아요..ㅋㅋ..ㅋ..ㅋ
나중에 기회가 되면 보겠습니당!! 감사합니당!!
